apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  selector:
    app: kafka-zookeeper
  sessionAffinity: None
  ports:
  - name: client
    protocol: TCP
    port: 2181
    targetPort: client
  type: ClusterIP
